### ISSUE TITLE
Remove Markus from contributors

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/site#10]
We talked, he does nothing here at all yet and has no plans to work on anything here. I have already pushed this change into the repo, just need to push to the site.

**Comment by eschabell** [comment]
Giving up on this. ;-)

**Comment by DuncanDoyle** [comment]
Still needs to be done. Assigning to myself and will chase.

**Comment by DuncanDoyle** [comment]
Site has been deprecated and redirects to developers.redhat.com. We don't explicitly list contributors there, so closing this issue.
