### ISSUE TITLE
Add Jason Milliron as contributor

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/site#11]
I have pushed this into the repo, please add to the site.

**Comment by eschabell** [comment]
Giving up on this. ;-)

**Comment by DuncanDoyle** [comment]
Still needs to done. Assigning to myself.

**Comment by DuncanDoyle** [comment]
The site has been deprecated and now redirects to developers.redhat.com. We don't explicitly list contributors there, so closing this issue.
